name: Generate and Commit File

on: [push]

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyYAML requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Execute script to generate file
      run: |
        cd aggregate
        python subscribe/collect.py  # 确保这里的路径正确

    - name: Configure Git
      run: |
        git config --global user.name ${{ secrets.name}}

    - name: Commit and push changes
      run: |
        git add aggregate/proxies.yaml
        git commit -m "Add generated output.yaml"
        git push
