name: Generate and Commit File

on:
  schedule:
    - cron: '0 */3 * * *'  
  workflow_dispatch: # 允许手动触发

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip3 install pyYAML requests tqdm pypushdeer
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Add group info
      run: |
        cd aggregate
        python subscribe/group.py ${{ secrets.PUSH_DEER_SECRET }}

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Commit and push changes
      run: |
        git add aggregate/proxies.yaml
        git commit -m "Add generated output.yaml"
        git push
